main:
  tasks:
    - path: data/codes-all.csv
      schema:
        missingValues:
          - ''
          - '-'
        fields:
          - name: Entity
            type: string
          - name: Currency
            type: string
          - name: AlphabeticCode
            type: string
          - name: NumericCode
            type: integer
          - name: MinorUnit
            type: integer
          - name: WithdrawalDate
            type: any
